create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email text, avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.businesses (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null check (char_length(trim(name)) > 0), business_type text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.profiles enable row level security;
alter table public.businesses enable row level security;
create policy "Users can view their own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "Owners can view their businesses" on public.businesses for select using (auth.uid() = owner_id);
create policy "Owners can create their businesses" on public.businesses for insert with check (auth.uid() = owner_id);
create policy "Owners can update their businesses" on public.businesses for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
create policy "Owners can delete their businesses" on public.businesses for delete using (auth.uid() = owner_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, full_name, email, avatar_url) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'), new.email, new.raw_user_meta_data->>'avatar_url') on conflict (id) do update set full_name = excluded.full_name, email = excluded.email, avatar_url = excluded.avatar_url, updated_at = now(); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();